# Changes here will be overwritten by Copier
_commit: "0514425"
_src_path: /Users/bruno/Documents/Workspace/oss/sources/cookiecutter-pypackage
add_me_as_contributor: true
copyright_year: "2022"
documentation: false
email: alla.brunoo@gmail.com
full_name: Bruno Alla
github_username: browniebroke
initial_commit: true
open_source_license: MIT
package_name: browniebroke_utils
project_name: Browniebroke Utils
project_short_description: A collections of small scripts.
project_slug: browniebroke-utils
run_poetry_install: true
setup_github: true
setup_pre_commit: true
version: 0.0.1
